# Use R language
language: r


matrix:
  include:
  # UNIX, old release (3.5.3)
  - r: oldrel
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran 
  # UNIX, release (3.6.1)
  - r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran  
  # MACOS, old release (3.5.3)
  - r: oldrel
    os: osx
    before_install:
      - sudo tlmgr install framed titling
      - sudo xcode-select --install
      - wget http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz
      - sudo tar -xzvf clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz -C/usr/local --strip-components 
      - sudo rm clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran
  # MACOS, release (3.6.1)
  - r: release
    os: osx
    before_install:
      - sudo tlmgr install framed titling
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran


