# Use R language
language: r


matrix:
  include:
  - r: oldrel
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran 
  - r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran     
  - r: oldrel
    os: osx
    osx_image: xcode7.3
    before_install:
      - sudo tlmgr install framed titling
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran
  - r: release
    os: osx
    osx_image: xcode7.3
    before_install:
      - sudo tlmgr install framed titling
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran


