# Use R language
language: r


matrix:
  include:
  # UNIX, old release (3.5.3)
  - r: oldrel
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran 
  # UNIX, release (3.6.1)
  - r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran  
  # MACOS, old release (3.5.3)
  - r: oldrel
    os: osx
    before_install:
      - sudo tlmgr install framed titling
      # deal with clang: error: unsupported option '-fopenmp'
      # for data.table v 1.12.4
      - Rscript -e "cat('Hello')"
      #- Rscript -e "install.packages('devtools')"
      #- Rscript -e "devtools::install_version('data.table', version = '1.12.2', repos = 'http://cloud.r-project.org', type='binary')"
      - Rscript -e "install.packages('https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.5/data.table_1.12.2.tgz')"
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran
  # MACOS, release (3.6.1)
  - r: release
    os: osx
    before_install:
      - sudo tlmgr install framed titling
    script:
      - R CMD build . --compact-vignettes=gs+qpdf --resave-data
      - R CMD check *tar.gz --as-cran


